### ISSUE TITLE
Update-Check bringt Fehler

### ISSUE THREAD

**Issue by Gummibando** [Tekl/openthesaurus-deutsch#3]
**Fehlerbeschreibung**
Der Update-Check in der Dictionary-Anwendung erzeugt einen Fehler.

**Wie lässt sich der Fehler nachvollziehen**
In den Einstellungen auf den "Auf Update prüfen" Button klicken.

**Erwartetes Verhalten**
Keine Ahnung, was müsste hier eigentlich passieren? 🤷🏻‍♂️

**Screenshots**
<img width="447" alt="image" src="https://user-images.githubusercontent.com/34392542/140503643-25e7e4ca-64a5-427c-a8af-e43f07bfafa1.png">

**Desktop (bitte vervollständgien):**
macOS-Version: 12.0.1 (21A559)

**Weitere Besonderheiten**
• Soweit ich es nachvollziehen kann (Test mit Proxyman), wird ein Request versendet, der Response ist eine HTML-Seite
• Der Fehler ist identisch in beiden Plugins (Thesaurus und Wörterbuch)
• Finder und Dictionary-App haben englische Spracheinstellung, Umstellung auf Deutsch macht aber keinen Unterschied

**Comment by Tekl** [comment]
Danke für den Hinweis. Da gab's einen Bug auf der Server-Seite, den ich jetzt behoben habe.
