### ISSUE TITLE
veralteter brew-Befehl in „Linkliste Wörterbuch-Plug-ins“ auf tekl.de

### ISSUE THREAD

**Issue by emsspree** [Tekl/openthesaurus-deutsch#5]
Hallo (und Sorry wenn das an dieser Stelle unangebracht ist),

auf Deiner Seite https://tekl.de/lexikon-plug-ins/weitere-lexikon-plug-ins 
steht bei _dict.cc Deutsch-Englisch Wörterbuch_ 
der alte Befehl für die Cask-Installation
<del>`brew cask install dictcc-en-de-dictionary-plugin`</del>,
<ins>`brew install --cask dictcc-en-de-dictionary-plugin`</ins> ist der aktuelle

**Comment by Tekl** [comment]
Danke für den Hinweis. Ist korrigiert.
